### ISSUE TITLE
[design] 로그인 페이지 디자인

### ISSUE THREAD

**Issue by h12j21-star** [13oosters/project-sns-react#2]
# 🐶오늘 할 일
- [x]  splash 페이지 디자인
- [x] 로그인 페이지 디자인
- [x] 이메일로 회원가입 디자인
- [x] 프로필 설정 디자인
- [x] form유효성 검사
- [ ] 회원가입 입력 데이터 전송

# 🐱코드리뷰 시 중점적으로 봐야할 사항
(커밋 후 복사하여 붙이고, 해당 커밋의 메인 기능에 대한 설명을 작성해주세요)

**Comment by Jxxunnn** [comment]
스플래시 기능 추가
