### ISSUE TITLE
[feat,design] Post 페이지 디자인, 기능구현

### ISSUE THREAD

**Issue by h12j21-star** [13oosters/project-sns-react#6]
# 🐶오늘 할 일
- [x] Post 페이지 마크업 작업
- [x] Post 페이지 디자인 작업
- [x] PostPage 디자인 (Card)
- [x] PostPage 디자인 (Comment)
- [x] PostPage 디자인 (Write)
- [x] axios post data받아오기
- [x] 게시글 상세페이지 데이터 출력하기
- [x] 게시글 삭제하기

# 🐱코드리뷰 시 중점적으로 봐야할 사항
(커밋 후 복사하여 붙이고, 해당 커밋의 메인 기능에 대한 설명을 작성해주세요)

**Comment by yubmun** [comment]
오늘 하루도 고생하셨습니다!
